services:
  - type: web
    name: srijal-portfolio-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd server && gunicorn app:app
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.8.12
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        value: https://sandeshbro-ux.github.io
    autoDeploy: true
