services:
  - type: web
    name: portfolio
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server/app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    staticPublishPath: ./
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
