services:
  - type: web
    name: srijal-portfolio
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0  # Changed to a more stable version
      - key: PORT
        value: 10000
    autoDeploy: true
    buildFilter:
      paths:
        - server/**
        - requirements.txt
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    healthCheckPath: /
