services:
  - type: web
    name: portfolio
    env: node
    buildCommand: npm ci
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: ACCESS_TOKEN_SECRET
        generateValue: true
    autoDeploy: true
    buildFilter:
      paths:
        - server/**
        - package.json
        - package-lock.json
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    healthCheckPath: /
