services:
  - type: web
    name: srijal-portfolio-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd server && PYTHONPATH=/opt/render/project/src python -m gunicorn app:app
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.8.12
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        value: https://srijal-2w45.onrender.com
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: STATIC_URL_PATH
        value: ''
      - key: STATIC_FOLDER
        value: /opt/render/project/src
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    autoDeploy: true
