services:
  - type: web
    name: portfolio
    env: node
    buildCommand: npm install
    startCommand: node server/server.js
    rootDirectory: ./ # Root directory is the repository root
    envVars:
      - key: NODE_ENV
        value: production
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
    autoDeploy: true
    buildFilter:
      paths:
        - server/**
        - package.json
        - package-lock.json
        - "*.js"
        - "*.html"
        - css/**
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000
    disk:
      name: portfolio-data
      mountPath: /data
      sizeGB: 1
    healthCheckPath: /
    numInstances: 1
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 80
      targetCPUPercent: 80
