services:
  - type: web
    name: srijal-portfolio
    runtime: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT server.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.12
      - key: PORT
        value: 10000
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: server.app
      - key: FLASK_DEBUG
        value: 0
      - key: DATABASE_URL
        value: sqlite:///data/messages.db
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        value: https://srijal-portfolio.onrender.com,https://sandeshbro-ux.github.io
      - key: PYTHONUNBUFFERED
        value: "true"
    autoDeploy: true
    buildFilter:
      paths:
        - server/**
        - requirements.txt
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000
    disk:
      name: sqlite-data
      mountPath: /data
      sizeGB: 1
    healthCheckPath: /
    plan: free
